### ISSUE TITLE
https on cms

### ISSUE THREAD

**Issue by smuco** [woonsan/hippo7-rproxy-nodejs#1]
Maybe not a reverse proxy problem but when using https to proxy the cms web, it will not reverse / but will reverse it correctly if you append a querystring parameter. For instance this call works (from nodejs log)

GET /cms/?0 HTTP/1.1 http://localhost:8080/cms/?0 200 

but not the following

GET /cms HTTP/1.1 http://localhost:8080/cms 302

which will reply with a redirect to /https,http://localhost/cms/

**Comment by woonsan** [comment]
Thank you, Saimir!
I was able to reproduce the problem as well. I'll fix it asap.
Cheers,
Woonsan

**Comment by woonsan** [comment]
Hi Saimir,
I've fixed the issue. Could you try it again?
Regards,
Woonsan
